This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./document.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file document.acr....done (9 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
